---
title: "Structural Equation Modelling With Lavaan in R"
author: "Adejumo Ridwan Suleiman"
editor: visual
format: 
  revealjs:
    preview-links: true
    chalkboard: 
      boardmarker-width: 5
from: markdown+emoji
---

## About the Presenter

# Introduction to SEM

## Overview of SEM

- Describe relationship between latent and observed variables by testing complex theoretical models
- Extension of multiple regression analysis and factor analysis
- Used in social science to test models where theoreticla constructs such as attitudes, beliefs and values are measure directly through multiple items.
- Used in pschchology, where latent variables such as personality traits or intelligence are meausred through questionnaires.

## Benefits of SEM

- Used to model complex relationships with inter related variables
- Provides estimates for direct and indirect effects.
- Ability to handle missing data and provide model parameter estimates in the presence of missing data.

## Limitations of SEM

- Large sample size to obtain reliable estimates of model parameters
- Requires a well specified theoretical model
- Difficult to learn and familiarity with statistical software and advanced statistical concepts.

## Applications of SEM
- Psychology
- Social Sciences
- Education
- Business


## Introduction to lavaan

# SEM Key Concepts

## Path diagrams and notation

## Latent and Observed variables

## Endogenous and Exogenous variables

## Direct and Indirect Effects

# Lavaan Overview

## Installing and loading the package

## Creating a model object

## Fitting the model

## Extracting results from the model

# Model Evaluation

## Fitting Indices and Goodness-of-fit tests

## Residual analysis and modification indices

## Parameter estimation and standard errors

## Model comparison and selection

# Case Study

# Summary

## Key takeaways

## Resources

## Q&A session
